
package webservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ExisteUsuarioExcepcion", targetNamespace = "http://webservice.java.main/")
public class ExisteUsuarioExcepcion_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExisteUsuarioExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExisteUsuarioExcepcion_Exception(String message, ExisteUsuarioExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ExisteUsuarioExcepcion_Exception(String message, ExisteUsuarioExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservice.ExisteUsuarioExcepcion
     */
    public ExisteUsuarioExcepcion getFaultInfo() {
        return faultInfo;
    }

}
