
package webservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NoExisteEdicionExcepcion", targetNamespace = "http://webservice.java.main/")
public class NoExisteEdicionExcepcion_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoExisteEdicionExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoExisteEdicionExcepcion_Exception(String message, NoExisteEdicionExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NoExisteEdicionExcepcion_Exception(String message, NoExisteEdicionExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservice.NoExisteEdicionExcepcion
     */
    public NoExisteEdicionExcepcion getFaultInfo() {
        return faultInfo;
    }

}
