
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;
import resources.Config;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WebServiceUsuarioService", targetNamespace = "http://webservice.java.main/", wsdlLocation = "http://127.0.0.1:9999/usuario?wsdl")
public class WebServiceUsuarioService
    extends Service
{

    private static final URL WEBSERVICEUSUARIOSERVICE_WSDL_LOCATION;
    private static final WebServiceException WEBSERVICEUSUARIOSERVICE_EXCEPTION;
    private static final QName WEBSERVICEUSUARIOSERVICE_QNAME = new QName("http://webservice.java.main/", "WebServiceUsuarioService");

    static {
    	String urlUsuario = Config.buildUrl(Config.get("WS_PORT_USUARIO"), "usuario");
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(urlUsuario);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEUSUARIOSERVICE_WSDL_LOCATION = url;
        WEBSERVICEUSUARIOSERVICE_EXCEPTION = e;
    }

    public WebServiceUsuarioService() {
        super(__getWsdlLocation(), WEBSERVICEUSUARIOSERVICE_QNAME);
    }

    public WebServiceUsuarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEUSUARIOSERVICE_QNAME, features);
    }

    public WebServiceUsuarioService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEUSUARIOSERVICE_QNAME);
    }

    public WebServiceUsuarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEUSUARIOSERVICE_QNAME, features);
    }

    public WebServiceUsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceUsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceUsuario
     */
    @WebEndpoint(name = "WebServiceUsuarioPort")
    public WebServiceUsuario getWebServiceUsuarioPort() {
        return super.getPort(new QName("http://webservice.java.main/", "WebServiceUsuarioPort"), WebServiceUsuario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceUsuario
     */
    @WebEndpoint(name = "WebServiceUsuarioPort")
    public WebServiceUsuario getWebServiceUsuarioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.java.main/", "WebServiceUsuarioPort"), WebServiceUsuario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEUSUARIOSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEUSUARIOSERVICE_EXCEPTION;
        }
        return WEBSERVICEUSUARIOSERVICE_WSDL_LOCATION;
    }

}
